<#
.SYNOPSIS
    Entry-point script for the Configuration Integrity Runner.

.DESCRIPTION
    Loads the ConfigIntegrity module and runs a full desired-vs-actual comparison
    for Azure VM resources. Writes a JSON report and exits with a non-zero code
    if the integrity status is FAIL.

.PARAMETER DesiredStatePath
    Path to the desired-state JSON file. Defaults to ../data/desired-state.json.

.PARAMETER ActualStatePath
    Path to the actual-state JSON file. Defaults to ../data/actual-state.json.
    In a real pipeline this file would be generated by Get-AzVM and serialised
    before calling this script.

.PARAMETER OutputPath
    Where to write the JSON report. Defaults to ../output/integrity-report.json.

.EXAMPLE
    ./Invoke-ConfigIntegrityCheck.ps1

.EXAMPLE
    ./Invoke-ConfigIntegrityCheck.ps1 `
        -DesiredStatePath ./data/desired-state.json `
        -ActualStatePath  ./data/actual-state.json  `
        -OutputPath       ./output/integrity-report.json
#>
[CmdletBinding()]
param (
    [string]$DesiredStatePath = (Join-Path $PSScriptRoot '../data/desired-state.json'),
    [string]$ActualStatePath  = (Join-Path $PSScriptRoot '../data/actual-state.json'),
    [string]$OutputPath       = (Join-Path $PSScriptRoot '../output/integrity-report.json')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module (Join-Path $PSScriptRoot 'ConfigIntegrity.psm1') -Force

$report = Invoke-ConfigIntegrityCheck `
    -DesiredStatePath $DesiredStatePath `
    -ActualStatePath  $ActualStatePath  `
    -OutputPath       $OutputPath

# Exit with non-zero code so GitHub Actions / CI pipelines can gate on failure.
if ($report.Summary.Status -eq 'FAIL') {
    Write-Warning "Integrity check FAILED — score $($report.Summary.IntegrityScore)% is below the 70% threshold."
    exit 1
}
